// api action types
export const API_REQUEST = "API_REQUEST";
export const API_REQUEST_START = "API_REQUEST_START";
export const API_REQUEST_END = "API_REQUEST_END";
export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";
export const API_REQUEST_FAILURE = "API_REQUEST_FAILURE";

// login user types
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_END = "LOGIN_USER_END";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

// logout user types
export const LOGOUT_USER_START = "LOGOUT_USER_START";
export const LOGOUT_USER_END = "LOGOUT_USER_END";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

// fetch swaps types
export const FETCH_SWAPS_START = "FETCH_SWAPS_START";
export const FETCH_SWAPS_END = "FETCH_SWAPS_END";
export const FETCH_SWAPS_SUCCESS = "FETCH_SWAPS_SUCCESS";
export const FETCH_SWAPS_FAILURE = "FETCH_SWAPS_FAILURE";

// create swap types
export const CREATE_SWAP_START = "CREATE_SWAP_START";
export const CREATE_SWAP_END = "CREATE_SWAP_END";
export const CREATE_SWAP_SUCCESS = "CREATE_SWAP_SUCCESS";
export const CREATE_SWAP_FAILURE = "CREATE_SWAP_FAILURE";

// get battery status types
export const GET_BATTERY_STATUS_START = "GET_BATTERY_STATUS_START";
export const GET_BATTERY_STATUS_END = "GET_BATTERY_STATUS_END";
export const GET_BATTERY_STATUS_SUCCESS = "GET_BATTERY_STATUS_SUCCESS";
export const GET_BATTERY_STATUS_FAILURE = "GET_BATTERY_STATUS_FAILURE";
